version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: workout_api_db
    environment:
      POSTGRES_USER: workout
      POSTGRES_PASSWORD: workout
      POSTGRES_DB: workoutapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
